object = SegmentTreeTest.cpp ../utils/SegmentTree.h
all: $(object)
	g++ -std=c++11 -o test_all $(object)
	./test_all
	rm test_all

SegmentTreeTest: ../utils/SegmentTree.h SegmentTreeTest.cpp
	g++ -std=c++11 -o SegmentTreeTest SegmentTreeTest.cpp
	./SegmentTreeTest
	rm SegmentTreeTest